### ISSUE TITLE
AP list showing intregrated instead of AP-ANT-345 

### ISSUE THREAD

**Issue by KennethAndersenAruba** [nickjvturner/badgerwifi-git#10]
when making the AP list with BWT, in the output for the Violet AP-634s and Aruba AP-ANT-345 antenna ends up as being "integrated" in the excel output.
![image](https://github.com/nickjvturner/badgerwifi-git/assets/134054262/708b9f50-549b-4a94-9e08-991d928a383d)

**Comment by nickjvturner** [comment]
fixed
