### ISSUE TITLE
Exit drop down is out of order

### ISSUE THREAD

**Issue by KennethAndersenAruba** [nickjvturner/badgerwifi-git#8]
Exit button in lower right corner works. The drop down menu link, does not.
See pictures for info
![image](https://github.com/nickjvturner/badgerwifi-git/assets/134054262/bd4cea62-661d-44c5-8a8b-1820a540c9c6)

**Comment by nickjvturner** [comment]
Good catch, my testing (not very much) routine on Windows did not catch this.
